<br>
<br>



<header class="gradientbg text-white">
<div class="container text-center ">
    
    <a  href="<?php echo $this->url(array('controller' => 'user', 'action' => 'dashboard')); ?>">
            <img src="/img/gbox.png" width="250" height="150"></a>
        </a>
    
       <p> <h1>Welchome to Ghostbox</h1></p>
<p> <h3>Join the Ghostbox club and never look back again!</h3></p>
    
    
</div>



</header>
    

    <section id="services" class="bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>Services we offer</h2>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut optio velit inventore, expedita quo laboriosam possimus ea consequatur vitae, doloribus consequuntur ex. Nemo assumenda laborum vel, labore ut velit dignissimos.</p>
          </div>
        </div>
      </div>
    </section>

    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>Contact us</h2>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.</p>
          </div>
        </div>
      </div>
    </section>

