<br /><br />
<div id="view-content">
	<p>View script for controller <b>User</b> and script/action name <b>list</b></p>
</div>

<?php
// the variable/array 'users' is generated and set in the
// controller 'user' and action 'list'
//
// all functions to the model user like 'getId()' and 'getFirstname() are
// functions of the model 'user' in the file 'models\user.php
?>

<div class="list-group">
<?php foreach($this->users as $user): ?>
<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'view', 'id' => $user->getId())); ?>" class="list-group-item ">
<div class="media">
  <div class="media-left">
      <img src="/img/user-icon.png" alt="Generic placeholder image">
  </div>
  <div class="media-body">
    <h5 class="media-heading"><?php echo '<b>' . $user->getLastname() . '</b>'; ?></h5>
    <p><?php echo $user->getFirstname() . ' ' ?></p>
  </div>
</div>
</a>
<?php endforeach; ?>
</div>